---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [— maxkb=1000]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/python/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [
          '.',
          '--exclude', '.git/', '--exclude', 'venv/', '--exclude', '.venv*']

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        types: [python]
        language: system
        entry: "env PYTHONPATH=./ pylint"
        args:
          - -E
          - --rcfile
          - .pylintrc

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: [-c=./.yamllint]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_tflint
        args:
          - --args=--minimum-failure-severity=error

  - repo: git@github.com:hari1710/aws_terraform_iac.git
    rev: v1.3
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: markdown-lint